version: "3.8"

services:
  backend:
    image: ghcr.io/nghyane/cookora-backend:latest
    container_name: cookora-backend
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      # Optional: Mount for logs persistence
      - ./logs:/app/logs
      # Optional: Mount for file uploads if needed
      - ./uploads:/app/tmp
    networks:
      - cookora-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  cookora-network:
    driver: bridge
