services:
  # Database services
  # postgres:
  #   image: pgvector/pgvector:pg17
  #   container_name: cookora-backend-postgres
  #   environment:
  #     POSTGRES_DB: cookora
  #     POSTGRES_USER: cookora
  #     POSTGRES_PASSWORD: cookora123
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   command: postgres -c shared_preload_libraries=pg_trgm,vector
  #   networks:
  #     - cookora-backend-network

  # Backend service
  backend:
    image: oven/bun:1.2.16
    container_name: cookora-backend
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://cookora:cookora123@postgres:5432/cookora
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: bun run start
    networks:
      - cookora-backend-network

# volumes:
# postgres_data:

networks:
  cookora-backend-network:
    driver: bridge
